version: '3.6'

services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    expose:
        - 8000
    environment:
        - DJANGO_READ_DOT_ENV_FILE=True
  nginx:
    build: ./nginx
    ports:
        - 1337:80
    depends_on:
        - web
