version: '3.7'

services:
  web:
    build: .
    command: gunicorn spotifydj.wsgi:application --bind 0.0.0.0:8000
    expose:
        - 8000
    env_file:
        - ./.env/.prod
  nginx:
    build: ./nginx
    expose:
        - 1337:80
    depends_on:
        - web
