# Generated by Django 2.0.8 on 2018-09-30 16:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('listening_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ListeningParty')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('playlists', models.ManyToManyField(to='api.Playlist')),
            ],
        ),
        migrations.AlterField(
            model_name='usergrant',
            name='timestamp_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
