# Generated by Django 2.0.8 on 2018-09-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergrant',
            name='timestamp_created',
            field=models.BigIntegerField(default=1538154932.399011),
        ),
    ]
