# Generated by Django 2.0.8 on 2018-09-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='user',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
