# Generated by Django 2.0.8 on 2018-09-28 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180928_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergrant',
            name='timestamp_created',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
