# Generated by Django 2.0.8 on 2018-09-30 17:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20180930_1638'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListeningParty',
            new_name='Party',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='listening_party',
            new_name='party',
        ),
    ]
