# Generated by Django 2.0.8 on 2018-09-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usergrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergrant',
            name='timestamp_created',
            field=models.BigIntegerField(default=1538076224.620704),
        ),
    ]
