# Generated by Django 2.0.8 on 2018-09-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180930_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='playlists',
            new_name='playlist',
        ),
    ]
