# Generated by Django 2.0.8 on 2018-09-30 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180930_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='uri',
            field=models.CharField(default=1, editable=False, max_length=64),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='song',
            name='id'
        ),
        migrations.AddField(
            model_name='song',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='playlist',
        ),
        migrations.AddField(
            model_name='song',
            name='playlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='api.Playlist'),
            preserve_default=False,
        ),
    ]
