# Generated by Django 2.0.8 on 2018-09-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180930_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='uri',
            field=models.CharField(max_length=64),
        ),
    ]
