# Generated by Django 2.0.8 on 2018-10-06 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181006_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songvote',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_songs', to='api.Song'),
        ),
    ]
