# Generated by Django 2.0.8 on 2018-09-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_logged_into_spotify',
            field=models.BooleanField(default=False),
        ),
    ]
